name: "Github pages APT repo"
description: "Setup and manage APT repo on Github pages"
inputs:
  github_token:
    description: "Github token with commit and push scope"
    required: true
  repo_supported_arch:
    description: "Newline-delimited list of supported architecture"
    required: true
  repo_supported_version:
    description: "Newline-delimited list of supported (linux) version"
    required: true
  file:
    description: "Newline-delimited list of .deb files"
    required: true
  file_target_version:
    description: "Newline-delimited list of version target of supplied .deb file"
    required: true
  public_key:
    description: "GPG public key for apt repo"
    required: false
  private_key:
    description: "GPG private key for signing apt repo"
    required: true
  key_passphrase:
    description: "Passphrase of GPG private key"
    required: false
  page_branch:
    description: "Branch of Github pages"
    required: false
    default: "gh-pages"
  repo_folder:
    description: "Location of APT repo folder relative to root of Github pages"
    required: false
    default: "repo"
  github_repository:
    description: "Target repository of the Github pages"
    required: false
  skip_duplicates:
    description: "Skip already added packages if same version, regardless of checksum"
    required: false
  debug:
    description: "Print debug log"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "upload-cloud"
  color: "red"
